### ISSUE TITLE
"Hide Scrollbar" Doesn't Work

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#61] opened 2023-03-04 00:53 UTC
0.39.0 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**Comment by raingart** [comment] 2023-03-04 08:10
Need more info - which option is not working?

- Only in watch page
- In live-chat
- 
Activate one of the options. For example the first(Only in watch page). I see no reason to hide the scrollbar on any page other than watch.

"Hide scrollbar" By itself, activating "Hide scrollbar" without internal options does nothing.

**Comment by raingart** [comment] 2023-03-04 08:11
This plugin is a response to a request. Where 2 requests were merged into 1 plugin

https://greasyfork.org/en/scripts/433360-nova-youtube/discussions/170167

**Closed** 2023-03-05 09:52 UTC

**Comment by raingart** [comment] 2023-03-25 08:21
I found out that the problem only affects Microsoft Edge (#68 ).
I've corrected it now. I'll post a beta version soon. Check for errors

The problem is that the data you specified (userAgent) does not specifically indicate the name of the browser. They almost all pretend to be google chrome
