### ISSUE TITLE
Floating progress bar chapter indicators not showing up on certain video.

### ISSUE THREAD

**Issue by Eisys** [raingart/Nova-YouTube-extension#97] opened 2023-08-04 17:44 UTC
So on this particular video the chapter indicators don't show up on Nova's progress bar.
https://www.youtube.com/watch?v=4aif-A9HQGU

This is the first and only video I've seen this on and it's an insignificant, tiny bug, but thought I'd let you know.

It happens on a brand new Chrome profile, only Tampermonkey installed. And in Nova only progress bar enabled.
 
Chrome Version 116.0.5845.49 (Official Build) beta (64-bit)
Tampermonkey 4.19.0
Nova 0.43.3

**Comment by raingart** [comment] 2023-08-07 11:05
fixed

**Comment by raingart** [comment] 2023-08-07 11:05
[fixed](https://gist.github.com/raingart/d61223c939fc1b02f0f7a14aaaa8cbbd)

The part that is responsible for obtaining the chapters is complex and rather complicated. It took two hours to remember how it works and figure out what the problem is.
This function allows you to display those chapters that are outside the YouTube player

**Comment by Eisys** [comment] 2023-08-07 22:35
You really didn't have to spend the time, seems like a tiny bug. But I suppose you want to be on top of thing as bugs come in so I appreciate it.

I tried the beta and I think it's half fixed.

For me the chapter indicators now only appear when in "default view" player mode. 
When the page loads on default view and I then go to cinema mode, indicators are there. But if page loads on cinema mode, they don't appear. 
Only this video, still. (I'm guessing because the chapters are auto generated by YT?) Everything else is normal.

**Comment by raingart** [comment] 2023-08-08 06:31
if I ignored this error. I would be pressed with time. I put it off for 3 days. Because I knew it would be difficult.

Probably the reason is that you probably have a smaller diagonal monitor. And YouTube does not load the block with chapters
I think if you activate the plugin "Description section in popup" then the chapters will always be loaded. Even though I'm not 100% sure

![Screenshot_105](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/f958d161-9e3b-4a91-8f7d-e7864436c2c0)

Here is my list of different types that I have tested:
https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/player/time-jump.js#L1-L29

for example, now the display of chapters in this format is broken
https://www.youtube.com/embed/JxTyMVPaOXY?autoplay=1

**Comment by Eisys** [comment] 2023-08-09 01:50
I understand, thank you for your effort.

My monitor is 32 inch 1440p.

I didn't realise getting the chapter locations is so difficult, I thought you simply "pulled" them from Youtube's own progress bar somehow.

**Comment by raingart** [comment] 2023-08-09 07:27
I just found out that the API scheme in embed is available for a certain time. And then it becomes unavailable.
I won't fix embed.

**Comment by raingart** [comment] 2023-08-09 07:30
>My monitor is 32 inch 1440p.

maybe I'm wrong. Try to activate the "Description section in popup" plugin. And if there are no gaps of error, then my theory is correct.

**Comment by Eisys** [comment] 2023-08-09 18:36
Well, with "Description section in popup" enabled, the indicators still don't pop up immediately, same conditions.

BUT they appear once I scroll down even a little bit or hover over the 'info🠋' button.
And even with it disabled, scrolling down makes them appear, so they seem to appear once the description fully loads.

**Comment by raingart** [comment] 2023-08-09 18:45
There is one idea is to move the block with chapters to the visible area and then return it. 
But I don't know if I will implement it. If you want I can try. But it doesn't bother me too much. 
I began to ignore problems with YouTube. For as many years as I have watched them, that immunity and indifference have appeared

**Comment by Eisys** [comment] 2023-08-09 19:15
No you don't have to. This is a very small bug and doesn't seem to affect too many videos, it doesn't bother me.

I've been using a progress bar without chapter indicators for years so it's not a big deal at all.

I think the issue can be closed, thank you for all your effort.

**Closed as completed** 2023-08-09 19:16 UTC
Labels: bug
