### ISSUE TITLE
Persistent Background Advertisements on YouTube

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#118] opened 2023-11-22 21:11 UTC
I hear advertisements playing in the background of my YT tabs. 
The problem occurs when loading my home feed and persists after closing and re-opening my tabs. 
The issue resolved itself after re-opening my browser.

 - Chrome: Version 119.0.6045.159 (Official Build) (arm64)
 - Tampermonkey 4.19.0
 - Nova 60.43.8

**Comment by raingart** [comment] 2023-11-22 21:26
if you're talking about the "Autopause when switching tabs" plugin, then yes, it sometimes skips playback
but I only tested with parameters "Autoplay on tab focus": "once for new tab"

If we are talking about why does Nova not block ads? that is, it is not due to the fact that I condemn blockers, but the fact that blocking advertising is technically difficult. The only “correct” way is to block and modify requests and data from them. uBlock origin handles this relatively well when using the built-in rules

You can test other scripts, maybe they will help you. But they are primitive, CSS hiding and emulation of closing advertising through clicks. But in the reviews of some of them everyone is happy

https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/player/ad-skip-button.js#L40-L44

The "Ad intro skip" plugin does not remove advertising as such. And clicks on the skip button that appears in the lower right corner. I don't know if this is advertising now. The plugin is probably outdated

Chrome used to have a flag `--autoplay-policy=user-gesture-required` that blocked autoplay of videos.

**Comment by bbksleazy** [comment] 2023-11-23 18:43
I have the same problem isn't not about it being an ad playing in the background but when clicking a video it loads it twice and the second one's audio plays and you can't stop it so its like you're watching a video and you might hear either an ad or the same video playing in the background and it can't be stopped
[Recording 2023-11-23 184201.zip](https://github.com/raingart/Nova-YouTube-extension/files/13452877/Recording.2023-11-23.184201.zip)

**Comment by bbksleazy** [comment] 2023-11-23 18:50
I have the same problem isn't not about it being an ad playing in the background but when clicking a video it loads it twice and the second one's audio plays and you can't stop it so its like you're watching a video and you might hear either an ad or the same video playing in the background and it can't be stopped

https://github.com/raingart/Nova-YouTube-extension/assets/131390099/3b11de88-f5ae-433b-b407-831d78879b99

**Comment by raingart** [comment] 2023-11-23 18:54
@bbksleazy I received your last message (you already sent a new one with sound). I didn't have such problems. I'm not sure what exactly the problem is. Can you send me your settings file?
@zkisaboss and canyou too?
So that I can compare the list of enabled plugins to determine which one is causing the failure.

A couple of years ago, Youtube began to hide some pages as an optimization and to reduce the number of requests to its servers. That is, when moving from one type of page to another, some elements are replaced by others. And Nova sometimes affected unnecessary hidden elements. A hidden instance of the player may be playing.

This is currently the most likely cause of the problem.

**Comment by bbksleazy** [comment] 2023-11-23 19:19
@raingart nvm it was a script called "Youtube adblock replace with embed" and having multiple anti-adblocks and adskippers on at the same time from tampermonkey causing the issue. So speaking for myself, it was just other scripts in tamper monkey

**Comment by raingart** [comment] 2023-11-23 19:27
@bbksleazy oh, thanks for clarifying

By the way, if your script gets rid of advertising by replacing the player with an iframe version, then this is the reason. This is the dumbest way that uses low-quality scripts

**Closed as completed** 2023-11-29 12:22 UTC
Labels: bug
