### ISSUE TITLE
Userscript version screenshot hang

### ISSUE THREAD

**Issue by fhoshino** [raingart/Nova-YouTube-extension#8] opened 2022-02-18 14:55 UTC
**Describe the bug**
1. Click on screenshot
2. Screenshot box appear on top right conner
3. CPU usage goes up
4. Right clicking the screenshot thumb nail hangs the tab

 - Browser [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)]
 - Monkey (is use userscript) [violentmonkey 2.13.0]
 - Extension version [0.23.0]

**Comment by fhoshino** [comment] 2022-02-18 15:03
I don't get errors from the console too, it's just hangs up the tab.
![brave_2022-02-18_23-03-22](https://user-images.githubusercontent.com/771955/154707910-43e78c44-c054-4d70-bfdc-cf7bde25c6d5.png)

**Comment by raingart** [comment] 2022-02-18 15:18
now I will create a special version with logging of this part. Please update it. And show what will be in the logs.
don't forget to turn off the old version.

https://gist.github.com/raingart/90dd0ae6bd0e63d57b33affbe46aa73a/raw/e5a45b0f2e5f14dbd4a38c8edc012d3a8222bd81/nova_test.user.js

**Comment by raingart** [comment] 2022-02-18 15:40
Do you have the option to execute [anydesk](https://anydesk.com/en/downloads/windows) so I can check it remotely?

**Comment by fhoshino** [comment] 2022-02-18 15:59
It takes arround 10 seconds to popup the thumb nail, and arround 20 seconds to the rightclick context menu, then saving seems no problem, but the close button takes another 10+ seconds to work

![brave_2022-02-18_23-57-21](https://user-images.githubusercontent.com/771955/154717365-6ecf0135-fe32-4469-8d1a-4d47e2674c0a.png)

**Comment by fhoshino** [comment] 2022-02-18 16:10
> Do you have the option to execute [anydesk](https://anydesk.com/en/downloads/windows) so I can check it remotely?

Could I have your email / telegram for contact?

**Comment by raingart** [comment] 2022-02-18 16:15
I disabled part of the code

https://gist.github.com/raingart/90dd0ae6bd0e63d57b33affbe46aa73a/raw/f24c45d8ad21559d2d06d9adb376c2253e550aa5/nova_test.user.js

if this version also hangs, then the problem is probably with Brave. 

If possible check on [chromium]
(https://github.com/Hibbiki/chromium-win64/releases/tag/v98.0.4758.82-r950365) 
or [old chromium](https://github.com/macchrome/chromium/releases ) 
or [chromium with AVX instructions](https://github.com/Alex313031/Thorium-Win/releases/tag/M100.0.4888.0)

my https://t.me/ori_on. But it's probably not worth it. Since the fact that Brave does not output "console.debug" to the console, but only "console.log" means that the differences from chromium are significant. And maybe that's the reason

**Closed** 2022-02-18 16:59 UTC
